### PR TITLE
Remove generated files from repo

### PR DESCRIPTION
**Pull request by mlachkar**
Hello,
Before merging this, you need to switch your github site to use gh-pages branch.

### CODE REVIEW

**Comment by julien-truffaut** [comment]
@mlachkar you are a wizard, I can't believe the publication to gh-pages worked from the first time. 

Thank you so much

**Comment by julien-truffaut** [comment]
@mlachkar just to let you know I re-added the images to master such as I develop the slides locally

**Comment by mlachkar** [comment]
Thanks ! I was happy to help.
The images was still there, just they were in slides/img ... but why not :) in that case we can remove the "cp -r slides/img docs/img" from the Makefile.

Just for information : to get the generation done locally, you just need to do : make depends, then make.

**Comment by julien-truffaut** [comment]
Ah I didn't notice sorry. When I test the html generation locally I generally do 
```scala
~tutOnly SideEffect.html
```

Such as I can get a quick feedback loop. So we need to set the `tutTargetDirectory` such as the img are available. As far as I can see, we can either choose `slides/docs` and move the images to `slides/docs/img` or use `/docs`. I guess the former might be better because it keeps all the slides related stuff in slides folder.

**Pull request merged**
